### ISSUE TITLE
Installation generator hangs

### ISSUE THREAD

**Issue by sambostock** [vinsol-spree-contrib/spree_admin_roles_and_access#24]
I'm running `bundle exec rails g spree_admin_roles_and_access:install`, but I get no feedback. Nothing prints to the console, the process just never does anything, and hangs forever.

If I interrupt, the stack trace is:
```
^C/Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client/run.rb:117:in `gets': Interrupt
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client/run.rb:117:in `verify_server_version'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client/run.rb:62:in `run'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client/run.rb:42:in `warm_run'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client/run.rb:35:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client/rails.rb:24:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /Users/sam/.rvm/gems/ruby-2.3.3@spree_vanilla/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/sam/dev/spree_vanilla/bin/spring:15:in `require'
	from /Users/sam/dev/spree_vanilla/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

Excerpt of `Gemfile`:
```
gem 'rails', '~> 5.0.2'

# Spree Dependencies
gem 'spree', '~> 3.2.0.rc3'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'
gem 'spree_admin_roles_and_access'
```

**Comment by donatoaz** [comment]
I am getting the same error upon running
`rails g spree:install --user_class=Spree::User`

```
gem 'rails', '~> 5.1.4'
gem 'spree', '~> 3.3.0'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'
```
